import {
  CloudFormationClient,
  DescribeStacksCommand,
} from "@aws-sdk/client-cloudformation";
import { writeFileSync, existsSync, mkdirSync, copyFileSync } from "fs";
import { join } from "path";
import * as dotenv from "dotenv";

dotenv.config({ path: join(__dirname, "../../../.env") });

const client = new CloudFormationClient({
  region: process.env.AWS_REGION ?? "us-east-1",
});

const STACKS = ["ServerStack", "AuthStack", "FrontendStack"];

const OUTPUT_MAP: Record<string, string> = {
  ApiUrl: "VITE_API_URL",
  UserPoolId: "VITE_USER_POOL_ID",
  UserPoolClientId: "VITE_USER_POOL_CLIENT_ID",
  FrontendUrl: "FRONTEND_URL",
};

async function getStackOutputs(stackName: string) {
  try {
    const res = await client.send(
      new DescribeStacksCommand({ StackName: stackName })
    );
    return res.Stacks?.[0]?.Outputs ?? [];
  } catch {
    console.warn(`Stack ${stackName} not found or not deployed yet — skipping`);
    return [];
  }
}

function backupEnv(envPath: string) {
  if (!existsSync(envPath)) return;
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = `${envPath}.${timestamp}.bak`;
  copyFileSync(envPath, backupPath);
  console.log(`Backed up existing .env to ${backupPath}`);
}

async function main() {
  console.log("Syncing environment variables from CloudFormation outputs...\n");

  const allOutputs = (await Promise.all(STACKS.map(getStackOutputs))).flat();

  const envLines: string[] = [
    "# Auto-generated by sync-env — do not edit manually",
    '# Run "pnpm sync-env" to regenerate after deploying',
    "",
  ];

  let found = 0;

  for (const output of allOutputs) {
    const key = output.OutputKey;
    const value = output.OutputValue;

    if (!key || !value) continue;

    const envKey = OUTPUT_MAP[key];
    if (!envKey) continue;

    envLines.push(`${envKey}=${value}`);
    console.log(`  ${envKey}=${value}`);
    found++;
  }

  if (found === 0) {
    console.error("No matching outputs found. Have you deployed the stacks?");
    process.exit(1);
  }

  const clientEnvDir = join(__dirname, "../../../packages/client");
  const clientEnvPath = join(clientEnvDir, ".env");

  if (!existsSync(clientEnvDir)) {
    mkdirSync(clientEnvDir, { recursive: true });
  }

  backupEnv(clientEnvPath);

  writeFileSync(clientEnvPath, envLines.join("\n") + "\n");
  console.log(`\nWritten to packages/client/.env (${found} variables)`);
}

main().catch((err) => {
  console.error("sync-env failed:", err.message);
  process.exit(1);
});
